name: Java CI with Maven and Run JAR

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Verify JAR file
        run: ls -la target/ && test -f target/spring-boot-github-actions-0.0.1.jar
      - name: Run the JAR file
        run: java -jar target/spring-boot-github-actions-0.0.1.jar
